"""Added checking logs table

Revision ID: 7d490de545f6
Revises: 
Create Date: 2017-10-25 02:03:32.483549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d490de545f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CheckingLogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jri', sa.String(length=16), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('txn_type', sa.Enum('DEBT', 'FOOD', 'TRANSPORT', 'RECREATION', 'RENT', 'LUXURY', 'SUPPLIES', 'SUBSCRIPTION', 'PAY', 'UNASSIGNED', name='transactiontype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CheckingLogs')
    # ### end Alembic commands ###
